name: footsapp
description: Footsapp application

version: 3.0.0+30001

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.0
  font_awesome_flutter: ^8.8.1
  cached_network_image: ^2.3.2+1
  rxdart: ^0.23.1
  provider: ^4.3.2+2
  http: ^0.12.2
  shared_preferences: ^0.5.12
  transparent_image:
  package_info: ^0.4.3
  keyboard_actions: ^3.3.0+1
  flutter_datetime_picker: ^1.4.0
  intl: ^0.16.1
  image_picker: ^0.6.7+11
  permission_handler: 5.0.1+1
  contacts_service: ^0.4.6
  after_layout: ^1.0.7+2
  flutter_staggered_animations:
  dio: ^3.0.10
  connection_status_bar: ^1.1.4
  firebase_core: ^0.5.0
  flushbar: 1.10.4
  firebase_messaging: ^7.0.0
  cloud_firestore: 0.14.0+2
  timeago: ^2.0.27
  image_cropper: 1.3.1
  slide_countdown_clock:
  flutter_google_places: ^0.2.3
  pin_code_text_field: 1.7.1
  flutter_speed_dial:
  flutter_html: ^1.0.2
  url_launcher: ^5.7.2
  firebase_dynamic_links: ^0.6.0
  share: ^0.6.5+2
  basic_utils: ^2.6.2
  esys_flutter_share: ^1.0.2
  weather: ^1.2.3
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  # service locator
  get_it: ^5.0.1
  auto_size_text: ^2.1.0
  google_sign_in: ^4.5.4
  flutter_login_facebook: ^0.2.1
  firebase_auth: ^0.18.0+1


dev_dependencies:
  flutter_launcher_icons: "^0.7.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/raw/
    - assets/docs/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: fonts/ProximaNova-AltBold.otf
        - asset: fonts/ProximaNova-Regular.otf
        - asset: fonts/ProximaNova-Thin.otf
        - asset: fonts/ProximaNova-ExtraBold.otf
        - asset: fonts/ProximaNova-Bold.otf
        - asset: fonts/ProximaNova-Black.otf
        - asset: fonts/ProximaNova-AltThin.otf
        - asset: fonts/ProximaNova-AltLight.otf
    - family: D-DIN
      fonts:
        - asset: fonts/D-DIN.otf
        - asset: fonts/D-DIN-Bold.otf
        - asset: fonts/D-DIN-Italic.otf
        - asset: fonts/D-DINCondensed-Bold.otf
        - asset: fonts/D-DINExp.otf
        - asset: fonts/D-DINExp-Bold.otf
        - asset: fonts/D-DINExp-Italic.otf
        - asset: fonts/D-DINCondensed.otf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
        - asset: fonts/Montserrat-Black.ttf
          weight: 900
          style: italic
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
